### ISSUE TITLE
openarc beta0 crash

### ISSUE THREAD

**Issue by seriv** [trusteddomainproject/OpenARC#111]
I am reopening issue #107, because I got a new crash when compiled openarc with '-O0 -g3'.
Here is the part of abrt daemone mail message about the crash:
<pre>
reason:         openarc killed by SIGABRT
cmdline:        /usr/sbin/openarc
executable:     /usr/sbin/openarc
package:        openarc-1.0.0-beta0.9.el7
component:      openarc
pid:            12160
pwd:            /
hostname:       mrouter01.cs.umd.edu
count:          1
abrt_version:   2.1.11
analyzer:       CCpp
architecture:   x86_64
event_log:     
global_pid:     12160
kernel:         3.10.0-862.3.2.el7.x86_64
last_occurrence: 1533636517
os_release:     Red Hat Enterprise Linux Server release 7.5 (Maipo)
pkg_arch:       x86_64
pkg_epoch:      0
pkg_name:       openarc
pkg_release:    beta0.9.el7
pkg_vendor:     (none)
pkg_version:    1.0.0
runlevel:       N 3
time:           Tue 07 Aug 2018 06:08:37 AM EDT
type:           CCpp
uid:            257
username:       openarc
uuid:           689d471f8ec3a329c69e9e20efa5288bd53521ee

core_backtrace:
:{   "signal": 6
:,   "executable": "/usr/sbin/openarc"
:,   "stacktrace":
:      [ {   "crash_thread": true
:        ,   "frames":
:              [ {   "address": 140386786140679
:                ,   "build_id": "85ea0ae559b53ab60d8548242cedd0e83f4816da"
:                ,   "build_id_offset": 221703
:                ,   "function_name": "raise"
:                ,   "file_name": "/usr/lib64/libc-2.17.so"
:                }
:              , {   "address": 140386786146552
:                ,   "build_id": "85ea0ae559b53ab60d8548242cedd0e83f4816da"
:                ,   "build_id_offset": 227576
:                ,   "function_name": "abort"
:                ,   "file_name": "/usr/lib64/libc-2.17.so"
:                }
:              , {   "address": 140386786111526
:                ,   "build_id": "85ea0ae559b53ab60d8548242cedd0e83f4816da"
:                ,   "build_id_offset": 192550
:                ,   "function_name": "__assert_fail_base"
:                ,   "file_name": "/usr/lib64/libc-2.17.so"
:                }
:              , {   "address": 140386786111698
:                ,   "build_id": "85ea0ae559b53ab60d8548242cedd0e83f4816da"
:                ,   "build_id_offset": 192722
:                ,   "file_name": "/usr/lib64/libc-2.17.so"
:                }
:              , {   "address": 4217546
:                ,   "build_id": "d338170fc7cca24bb64328cdef7d340516df1ae7"
:                ,   "build_id_offset": 23242
:                ,   "function_name": "arcf_config_free"
:                ,   "file_name": "/usr/sbin/openarc"
:                }
:              , {   "address": 4244836
:                ,   "build_id": "d338170fc7cca24bb64328cdef7d340516df1ae7"
:                ,   "build_id_offset": 50532
:                ,   "function_name": "main"
:                ,   "file_name": "/usr/sbin/openarc"
:                } ]
:        } ]
:}
</pre>
And here is backtrace on the coredump:
<pre>
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `/usr/sbin/openarc'.
Program terminated with signal 6, Aborted.
#0  0x00007fae5884e207 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56        return INLINE_SYSCALL (tgkill, 3, pid, selftid, sig);
(gdb) bt
#0  0x00007fae5884e207 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007fae5884f8f8 in __GI_abort () at abort.c:90
#2  0x00007fae58847026 in __assert_fail_base (fmt=0x7fae589a2520 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=assertion@entry=0x4107b3 "conf->conf_refcnt == 0", file=file@entry=0x4105a2 "openarc.c", line=line@entry=1328, 
    function=function@entry=0x411c00 <__PRETTY_FUNCTION__.8701> "arcf_config_free") at assert.c:92
#3  0x00007fae588470d2 in __GI___assert_fail (assertion=0x4107b3 "conf->conf_refcnt == 0", file=0x4105a2 "openarc.c", line=1328, function=0x411c00 <__PRETTY_FUNCTION__.8701> "arcf_config_free") at assert.c:101
#4  0x0000000000405aca in arcf_config_free (conf=0xd00030) at openarc.c:1328
#5  0x000000000040c564 in main (argc=1, argv=0x7ffc57c873b8) at openarc.c:5020
(gdb)
</pre>
and here are slightly anonymized lines from maillog around this time:
<pre>
Aug  7 06:08:33 mrouter01.cs.umd.edu postfix/smtpd[21373]: 033A4407093B: client=barracuda00.cs.umd.edu[128.8.128.201]
Aug  7 06:08:33 mrouter01.cs.umd.edu postfix/cleanup[24714]: 033A4407093B: message-id=<1533636512.9mfgps3uporm1l3y.checksmtpsend@itmon01.cs.umd.edu>
Aug  7 06:08:33 mrouter01.cs.umd.edu authentication_milter[26126]: 033A4407093B: DKIMResult: No DKIM headers
Aug  7 06:08:33 mrouter01.cs.umd.edu authentication_milter[26126]: 033A4407093B: PreHeader: Authentication-Results: mrouter01.cs.umd.edu;#012    dkim=none (no signatures found);#012    x-return-mx=warn header.domain=nagios.cs.umd.edu policy.org_domain=umd.edu policy.is_org=no (A Record found);#012    x-return-mx=warn smtp.domain=nagios.cs.umd.edu policy.org_domain=umd.edu policy.is_org=no (A Record found);#012    x-trusted-ip=pass
Aug  7 06:08:33 mrouter01.cs.umd.edu postfix/qmgr[11091]: 033A4407093B: from=<nagios@nagios.cs.umd.edu>, size=1825, nrcpt=1 (queue active)
Aug  7 06:08:33 mrouter01.cs.umd.edu postfix/smtpd[21373]: disconnect from barracuda00.cs.umd.edu[128.8.128.201]
Aug  7 06:08:33 mrouter01.cs.umd.edu postfix/smtp[21573]: Untrusted TLS connection established to imap00.cs.umd.edu[128.8.128.111]:25: TLSv1.2 with cipher AECDH-AES256-SHA (256/256 bits)
Aug  7 06:08:33 mrouter01.cs.umd.edu postfix/smtp[21573]: 033A4407093B: to=<user_for_testing@cs.umd.edu>, relay=imap00.cs.umd.edu[128.8.128.111]:25, delay=1, delays=1/0/0/0.01, dsn=2.0.0, status=sent (250 2.0.0 Ok: queued as EACB680CABE0)
Aug  7 06:08:33 mrouter01.cs.umd.edu postfix/qmgr[11091]: 033A4407093B: removed
Aug  7 06:08:37 mrouter01.cs.umd.edu postfix/smtpd[21373]: connect from barracuda00.cs.umd.edu[128.8.128.201]
Aug  7 06:08:37 mrouter01.cs.umd.edu openarc[12160]: OpenARC Filter: mi_stop=1
Aug  7 06:08:37 mrouter01.cs.umd.edu openarc[12160]: OpenARC Filter v1.0.0 terminating with status 0, errno = 0
Aug  7 06:08:37 mrouter01.cs.umd.edu postfix/smtpd[21373]: Anonymous TLS connection established from barracuda00.cs.umd.edu[128.8.128.201]: TLSv1.2 with cipher AECDH-AES256-SHA (256/256 bits)
Aug  7 06:08:37 mrouter01.cs.umd.edu postfix/smtpd[21373]: warning: milter inet:127.0.0.1:8889: can't read SMFIC_MAIL reply packet header: Success
Aug  7 06:08:37 mrouter01.cs.umd.edu postfix/smtpd[21373]: NOQUEUE: milter-reject: MAIL from barracuda00.cs.umd.edu[128.8.128.201]: 451 4.7.1 Service unavailable - try again later; from=<no-reply@alertsp.chase.com> proto=ESMTP helo=<barracuda.cs.umd.edu>
Aug  7 06:08:37 mrouter01.cs.umd.edu postfix/smtpd[21373]: disconnect from barracuda00.cs.umd.edu[128.8.128.201]
</pre>

**Comment by mskucherawy** [comment]
During shutdown we're trying to free a configuration context that might still be in use.  There's an assertion guard in there to make sure this doesn't happen normally, but during shutdown it should be fine.  We can arrange to skip the guard in that case.
