### ISSUE TITLE
malloc(): memory corruption in arc_validate_seal()

### ISSUE THREAD

**Issue by mdomsch** [trusteddomainproject/OpenARC#30]
CentOS 6.x (latest) with branch flowerysong/build-fixes (so that it builds at all):

```
commit 1df751be9fa5ecd0ed64cd7abe2257ee857ff0b9
Author: Paul Arthur <paul.arthur@flowerysong.com>
Date:   Mon Jun 12 03:38:40 2017 +0000
```
```
*** glibc detected *** /usr/sbin/openarc: malloc(): memory corruption: 0xb600e9e8 ***
======= Backtrace: =========
/lib/libc.so.6(+0x70bb1)[0x435bb1]
/lib/libc.so.6(+0x74c30)[0x439c30]
/lib/libc.so.6(__libc_malloc+0x57)[0x43a1b7]
/usr/lib/libcrypto.so.10(+0x40eef)[0x1f7eef]
/usr/lib/libcrypto.so.10(CRYPTO_malloc+0x79)[0x1f8459]
/usr/lib/libcrypto.so.10(RSA_new_method+0x39)[0x24f429]
/usr/lib/libcrypto.so.10(RSA_new+0x1f)[0x24f6af]
/usr/lib/libcrypto.so.10(+0x9b84d)[0x25284d]
/usr/lib/libcrypto.so.10(+0xe20dc)[0x2990dc]
/usr/lib/libcrypto.so.10(ASN1_item_ex_d2i+0xba9)[0x29c399]
/usr/lib/libcrypto.so.10(ASN1_item_d2i+0x66)[0x29cb26]
/usr/lib/libcrypto.so.10(d2i_RSAPublicKey+0x36)[0x2529e6]
/usr/lib/libcrypto.so.10(+0x9d157)[0x254157]
/usr/lib/libcrypto.so.10(X509_PUBKEY_get+0xc1)[0x292371]
/usr/lib/libcrypto.so.10(d2i_PUBKEY+0x58)[0x2929d8]
/usr/lib/libcrypto.so.10(ASN1_d2i_bio+0x49)[0x28e599]
/usr/lib/libcrypto.so.10(d2i_PUBKEY_bio+0x39)[0x2bb809]
/usr/lib/libopenarc.so.0(arc_eom+0x544)[0x135814]
/usr/sbin/openarc[0x804d096]
/usr/lib/libmilter.so.1.0(+0x4849)[0x143849]
/usr/lib/libmilter.so.1.0(mi_engine+0x1e6)[0x143aa6]
/usr/lib/libmilter.so.1.0(mi_handle_session+0x60)[0x145e80]
/usr/lib/libmilter.so.1.0(+0x564e)[0x14464e]
/lib/libpthread.so.0(+0x6bc9)[0x3b0bc9]
/lib/libc.so.6(clone+0x5e)[0x4a804e]
======= Memory map: ========
00110000-0012e000 r-xp 00000000 fc:01 1180262    /lib/ld-2.12.so
0012e000-0012f000 r--p 0001e000 fc:01 1180262    /lib/ld-2.12.so
0012f000-00130000 rw-p 0001f000 fc:01 1180262    /lib/ld-2.12.so
00130000-00131000 r-xp 00000000 00:00 0          [vdso]
00131000-0013e000 r-xp 00000000 fc:01 674480     /usr/lib/libopenarc.so.0.0.0
0013e000-0013f000 rw-p 0000c000 fc:01 674480     /usr/lib/libopenarc.so.0.0.0
0013f000-0014b000 r-xp 00000000 fc:01 655768     /usr/lib/libmilter.so.1.0.1
0014b000-0014c000 rw-p 0000b000 fc:01 655768     /usr/lib/libmilter.so.1.0.1
0014c000-0014e000 rw-p 00000000 00:00 0
0014e000-001b0000 r-xp 00000000 fc:01 671777     /usr/lib/libssl.so.1.0.1e
001b0000-001b3000 r--p 00061000 fc:01 671777     /usr/lib/libssl.so.1.0.1e
001b3000-001b7000 rw-p 00064000 fc:01 671777     /usr/lib/libssl.so.1.0.1e
001b7000-00368000 r-xp 00000000 fc:01 657385     /usr/lib/libcrypto.so.1.0.1e
00368000-00378000 r--p 001b0000 fc:01 657385     /usr/lib/libcrypto.so.1.0.1e
00378000-0037f000 rw-p 001c0000 fc:01 657385     /usr/lib/libcrypto.so.1.0.1e
0037f000-00382000 rw-p 00000000 00:00 0
00382000-00397000 r-xp 00000000 fc:01 1182007    /lib/libresolv-2.12.so
00397000-00399000 r--p 00015000 fc:01 1182007    /lib/libresolv-2.12.so
00399000-0039a000 rw-p 00017000 fc:01 1182007    /lib/libresolv-2.12.so
0039a000-0039c000 rw-p 00000000 00:00 0
0039c000-003a9000 r-xp 00000000 fc:01 669356     /usr/lib/libbsd.so.0.6.0
003a9000-003aa000 rw-p 0000d000 fc:01 669356     /usr/lib/libbsd.so.0.6.0
003aa000-003c1000 r-xp 00000000 fc:01 1180635    /lib/libpthread-2.12.so
003c1000-003c2000 r--p 00016000 fc:01 1180635    /lib/libpthread-2.12.so
003c2000-003c3000 rw-p 00017000 fc:01 1180635    /lib/libpthread-2.12.so
003c3000-003c5000 rw-p 00000000 00:00 0
003c5000-00556000 r-xp 00000000 fc:01 1180392    /lib/libc-2.12.so
00556000-00558000 r--p 00191000 fc:01 1180392    /lib/libc-2.12.so
00558000-00559000 rw-p 00193000 fc:01 1180392    /lib/libc-2.12.so
00559000-0055c000 rw-p 00000000 00:00 0
0055c000-0059a000 r-xp 00000000 fc:01 1181866    /lib/libgssapi_krb5.so.2.2
0059a000-0059b000 r--p 0003e000 fc:01 1181866    /lib/libgssapi_krb5.so.2.2
0059b000-0059c000 rw-p 0003f000 fc:01 1181866    /lib/libgssapi_krb5.so.2.2
0059c000-00673000 r-xp 00000000 fc:01 1181870    /lib/libkrb5.so.3.3
00673000-00679000 r--p 000d6000 fc:01 1181870    /lib/libkrb5.so.3.3
00679000-0067a000 rw-p 000dc000 fc:01 1181870    /lib/libkrb5.so.3.3
0067a000-0067d000 r-xp 00000000 fc:01 1182034    /lib/libcom_err.so.2.1
0067d000-0067e000 r--p 00002000 fc:01 1182034    /lib/libcom_err.so.2.1
0067e000-0067f000 rw-p 00003000 fc:01 1182034    /lib/libcom_err.so.2.1
0067f000-006a7000 r-xp 00000000 fc:01 1180459    /lib/libk5crypto.so.3.1
006a7000-006a8000 r--p 00028000 fc:01 1180459    /lib/libk5crypto.so.3.1
006a8000-006a9000 rw-p 00029000 fc:01 1180459    /lib/libk5crypto.so.3.1
006a9000-006aa000 rw-p 00000000 00:00 0
006aa000-006ad000 r-xp 00000000 fc:01 1181684    /lib/libdl-2.12.so
006ad000-006ae000 r--p 00002000 fc:01 1181684    /lib/libdl-2.12.so
006ae000-006af000 rw-p 00003000 fc:01 1181684    /lib/libdl-2.12.so
006af000-006c1000 r-xp 00000000 fc:01 1183820    /lib/libz.so.1.2.3
006c1000-006c2000 r--p 00011000 fc:01 1183820    /lib/libz.so.1.2.3
006c2000-006c3000 rw-p 00012000 fc:01 1183820    /lib/libz.so.1.2.3
006c3000-006cd000 r-xp 00000000 fc:01 1181871    /lib/libkrb5support.so.0.1
006cd000-006ce000 r--p 00009000 fc:01 1181871    /lib/libkrb5support.so.0.1
006ce000-006cf000 rw-p 0000a000 fc:01 1181871    /lib/libkrb5support.so.0.1
006cf000-006d1000 r-xp 00000000 fc:01 1183845    /lib/libkeyutils.so.1.3
006d1000-006d2000 r--p 00001000 fc:01 1183845    /lib/libkeyutils.so.1.3
006d2000-006d3000 rw-p 00002000 fc:01 1183845    /lib/libkeyutils.so.1.3
006d3000-006f0000 r-xp 00000000 fc:01 1181861    /lib/libselinux.so.1
006f0000-006f1000 r--p 0001d000 fc:01 1181861    /lib/libselinux.so.1
006f1000-006f2000 rw-p 0001e000 fc:01 1181861    /lib/libselinux.so.1
006f2000-006fe000 r-xp 00000000 fc:01 1181752    /lib/libnss_files-2.12.so
006fe000-006ff000 r--p 0000b000 fc:01 1181752    /lib/libnss_files-2.12.so
006ff000-00700000 rw-p 0000c000 fc:01 1181752    /lib/libnss_files-2.12.so
00700000-0071d000 r-xp 00000000 fc:01 1180036    /lib/libgcc_s-4.4.7-20120601.so.1
0071d000-0071e000 rw-p 0001d000 fc:01 1180036    /lib/libgcc_s-4.4.7-20120601.so.1
08048000-08057000 r-xp 00000000 fc:01 674479     /usr/sbin/openarc
08057000-08058000 rw-p 0000f000 fc:01 674479     /usr/sbin/openarc
08058000-08089000 rw-p 00000000 00:00 0          [heap]
b5e00000-b5e21000 rw-p 00000000 00:00 0
b5e21000-b5f00000 ---p 00000000 00:00 0
b6000000-b6021000 rw-p 00000000 00:00 0
b6021000-b6100000 ---p 00000000 00:00 0
b61ef000-b61f0000 ---p 00000000 00:00 0
b61f0000-b6bf0000 rw-p 00000000 00:00 0
b6bf0000-b6bf1000 ---p 00000000 00:00 0
b6bf1000-b75f1000 rw-p 00000000 00:00 0
b75f1000-b75f2000 ---p 00000000 00:00 0
b75f2000-b7ff7000 rw-p 00000000 00:00 0
b7ffd000-b8000000 rw-p 00000000 00:00 0
bffea000-c0000000 rw-p 00000000 00:00 0          [stack]

Program received signal SIGABRT, Aborted.
[Switching to Thread 0xb6befb70 (LWP 27213)]
0x00130424 in __kernel_vsyscall ()
Missing separate debuginfos, use: debuginfo-install keyutils-libs-1.4-5.el6.i686 krb5-libs-1.10.3-65.el6.i686 libcom_err-1.41.12-23.el6.i686 libgcc-4.4.7-18.el6.i686 libselinux-2.0.94-7.el6.i686 openssl-1.0.1e-57.el6.i686
(gdb) bt
#0  0x00130424 in __kernel_vsyscall ()
#1  0x003ef781 in raise (sig=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:64
#2  0x003f105a in abort () at abort.c:92
#3  0x0042f645 in __libc_message (do_abort=2, fmt=0x51e810 "*** glibc detected *** %s: %s: 0x%s ***\n") at ../sysdeps/unix/sysv/linux/libc_fatal.c:198
#4  0x00435bb1 in malloc_printerr (action=<value optimized out>, str=<value optimized out>, ptr=0xb600e9e8, ar_ptr=0xb6000010) at malloc.c:6360
#5  0x00439c30 in _int_malloc (av=0xb6000010, bytes=88) at malloc.c:4451
#6  0x0043a1b7 in __libc_malloc (bytes=88) at malloc.c:3667
#7  0x001f7eef in ?? () from /usr/lib/libcrypto.so.10
#8  0x001f8459 in CRYPTO_malloc () from /usr/lib/libcrypto.so.10
#9  0x0024f429 in RSA_new_method () from /usr/lib/libcrypto.so.10
#10 0x0024f6af in RSA_new () from /usr/lib/libcrypto.so.10
#11 0x0025284d in ?? () from /usr/lib/libcrypto.so.10
#12 0x002990dc in ?? () from /usr/lib/libcrypto.so.10
#13 0x0029c399 in ASN1_item_ex_d2i () from /usr/lib/libcrypto.so.10
#14 0x0029cb26 in ASN1_item_d2i () from /usr/lib/libcrypto.so.10
#15 0x002529e6 in d2i_RSAPublicKey () from /usr/lib/libcrypto.so.10
#16 0x00254157 in ?? () from /usr/lib/libcrypto.so.10
#17 0x00292371 in X509_PUBKEY_get () from /usr/lib/libcrypto.so.10
#18 0x002929d8 in d2i_PUBKEY () from /usr/lib/libcrypto.so.10
#19 0x0028e599 in ASN1_d2i_bio () from /usr/lib/libcrypto.so.10
#20 0x002bb809 in d2i_PUBKEY_bio () from /usr/lib/libcrypto.so.10
#21 0x00135814 in arc_validate_seal (msg=0xb60026b8) at arc.c:1963
#22 arc_eom (msg=0xb60026b8) at arc.c:2593
#23 0x0804d096 in mlfi_eom (ctx=0x8079f18) at openarc.c:3230
#24 0x00143849 in st_bodyend (g=0xb6bef290) at engine.c:1614
#25 0x00143aa6 in mi_engine (ctx=0x8079f18) at engine.c:405
#26 0x00145e80 in mi_handle_session (ctx=0x8079f18) at handler.c:45
#27 0x0014464e in mi_thread_handle_wrapper (arg=0x8079f18) at listener.c:579
#28 0x003b0bc9 in start_thread (arg=0xb6befb70) at pthread_create.c:301
#29 0x004a804e in clone () at ../sysdeps/unix/sysv/linux/i386/clone.S:133
(gdb) frame 21
#21 0x00135814 in arc_validate_seal (msg=0xb60026b8) at arc.c:1963
1963            pkey = d2i_PUBKEY_bio(key, NULL);
(gdb) print *msg
$1 = {arc_partial = false, arc_key = 0xb600e4b8 "0\201\237\060\r\006\t*\206H\206\367\r\001\001\001\005", arc_error = 0x0,
  arc_hdrlist = 0xb600ce00 "DMARC-Filter", arc_domain = 0xb600a63e "domsch.com", arc_selector = 0xb600a64c "seal-20170618", arc_authservid = 0x0,
  arc_b64sig = 0x0,
  arc_b64key = 0xb600ec62 "MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQC/0rsJcrwka83WFZ9yUUKGI3aZ7lGnTTelnJ3h9PKkwc08vpTDxCz85XkME6XOTU5F8eJ4ORMuHDv72zRwOgbzmLpnR02LPYOCC4/UyBCNFEo2JYRr9t3apIqnSEBoaEBxZ+n5tX1tOK3wmmvRwOmcykWKOQjROFa6"..., arc_signature = 0x0, arc_dnssec_key = -1, arc_signalg = 1, arc_nsets = 1,
  arc_margin = 75, arc_state = 3, arc_hdrcnt = 32, arc_timeout = 0, arc_keybits = 0, arc_keytype = 0, arc_hashtype = 0, arc_flags = 0, arc_query = 0,
  arc_timestamp = 1497848888, arc_sigttl = 0, arc_siglen = 0, arc_keylen = 162, arc_errorlen = 0, arc_b64keylen = 216, arc_bodylen = 222, arc_canonhdr = 1,
  arc_canonbody = 0, arc_cstate = 2, arc_sigerror = 0, arc_querymethods = 0x0, arc_xtags = 0x0, arc_canonbuf = 0xb60074c0, arc_hdrbuf = 0xb60074a8,
  arc_sealcanon = 0xb60036a0, arc_sealcanons = 0xb6003640, arc_hdrcanon = 0xb60035a0, arc_bodycanon = 0xb60035f0, arc_canonhead = 0xb60035a0,
  arc_canontail = 0xb60036a0, arc_hhead = 0xb6002790, arc_htail = 0xb600a5b8, arc_sealhead = 0x0, arc_sealtail = 0x0, arc_kvsethead = 0xb6001e40,
  arc_kvsettail = 0xb600f198, arc_sets = 0xb6003590, arc_library = 0x8069b88, arc_user_context = 0x0}
(gdb) print *key
$3 = {method = 0x379f20, callback = 0, cb_arg = 0x0, init = 1, shutdown = 1, flags = 512, retry_reason = 0, num = 0, ptr = 0xb600ef88, next_bio = 0x0,
  prev_bio = 0x0, references = 1, num_read = 162, num_write = 0, ex_data = {sk = 0x0, dummy = 0}}

```
```
$ more /etc/openarc.conf
## Basic OpenARC config file for verification only
## See openarc.conf(5) or /usr/share/doc/openarc-0.1.0/openarc.conf.sample for more
PidFile /var/run/openarc/openarc.pid
#Mode   v
Syslog  yes
#Umask   002
UserID  openarc:openarc
#Socket local:/var/run/openarc/openarc.socket
Socket  inet:8894@localhost

## After setting Mode to "sv", running
## openarc-genkey -D /etc/openarc -s key -d `hostname --domain`
## and putting /etc/openarc
#Canonicalization        relaxed/simple
#Domain                  example.com # change to domain
#Selector                key
#KeyFile                 /etc/openarc/key.private
Domain domsch.com
KeyFile /etc/openarc/keys/domsch.com/seal-20170618.private
Selector seal-20170618
SignatureAlgorithm rsa-sha256
#PeerList 127.0.0.1
#PeerList ::1
MilterDebug 6
EnableCoredumps yes

```

**Comment by juh** [comment]
See pull request #54.
